// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {ISealedCashVerifier} from "./interfaces/ISealedCashVerifier.sol";
import {IUltraHonkVerifier} from "./interfaces/IUltraHonkVerifier.sol";

/// @notice Production adapter for the setup-free Noir/UltraHonk verifier.
/// @dev The verifier bytecode is generated by bb.js for verifierTarget=evm.
/// Unlike the development Groth16 adapter this contract has no trusted setup
/// key, and refuses malformed public-input vectors before forwarding them.
contract SealedCashUltraHonkAdapter is ISealedCashVerifier {
    uint256 public constant BN254_SCALAR_MODULUS =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;
    IUltraHonkVerifier public immutable generatedVerifier;

    error NonCanonicalField();
    error InvalidProofEncoding();

    constructor(address generatedVerifier_) {
        require(generatedVerifier_ != address(0), "zero verifier");
        generatedVerifier = IUltraHonkVerifier(generatedVerifier_);
    }

    function verifyProof(bytes calldata proof, PublicInputs calldata inputs)
        external
        view
        returns (bool)
    {
        if (proof.length == 0) revert InvalidProofEncoding();
        uint256[] memory values = new uint256[](21);
        values[0] = inputs.chainId;
        values[1] = uint256(uint160(inputs.pool));
        values[2] = uint256(inputs.domain);
        values[3] = uint256(inputs.protocolVersion);
        values[4] = uint256(inputs.circuitVersion);
        values[5] = uint256(inputs.operation);
        values[6] = uint256(inputs.root);
        values[7] = uint256(uint160(inputs.asset));
        values[8] = inputs.publicAmount;
        values[9] = inputs.isDeposit ? 1 : 0;
        values[10] = uint256(uint160(inputs.recipient));
        values[11] = uint256(uint160(inputs.relayer));
        values[12] = inputs.relayerFee;
        values[13] = uint256(inputs.inputCount);
        values[14] = uint256(inputs.outputCount);
        values[15] = uint256(inputs.nullifiers[0]);
        values[16] = uint256(inputs.nullifiers[1]);
        values[17] = uint256(inputs.commitments[0]);
        values[18] = uint256(inputs.commitments[1]);
        values[19] = uint256(inputs.ciphertextHashes[0]);
        values[20] = uint256(inputs.ciphertextHashes[1]);
        bytes32[] memory publicInputs = new bytes32[](21);
        for (uint256 i; i < values.length; ++i) {
            if (values[i] >= BN254_SCALAR_MODULUS) revert NonCanonicalField();
            publicInputs[i] = bytes32(values[i]);
        }
        try generatedVerifier.verify(proof, publicInputs) returns (bool valid) {
            return valid;
        } catch {
            return false;
        }
    }
}