// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {ISealedCashHasher} from "./interfaces/ISealedCashHasher.sol";

/// @title SealedCashPoseidonHasher
/// @notice BN254 Poseidon(2) primitive used by the privacy tree.
/// @dev The implementation is deliberately kept behind a small, immutable
///      adapter boundary.  Deployments must provide the bytecode generated by
///      circomlib's Poseidon(2) generator; this contract refuses an empty or
///      non-contract primitive.  Keeping the boundary explicit prevents the
///      keccak-based development hasher from accidentally reaching production.
contract SealedCashPoseidonHasher is ISealedCashHasher {
    uint256 public constant BN254_SCALAR_MODULUS =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;

    address public immutable poseidon;

    error ZeroAddress();
    error NotAContract();
    error PoseidonCallFailed();

    constructor(address poseidon_) {
        if (poseidon_ == address(0)) revert ZeroAddress();
        uint256 size;
        assembly ("memory-safe") { size := extcodesize(poseidon_) }
        if (size == 0) revert NotAContract();
        poseidon = poseidon_;
    }

    /// @dev `poseidon(uint256[2])` is the canonical circomlibjs ABI.  The
    ///      returned field element is checked rather than reduced so malformed
    ///      primitives fail closed.
    function hashLeftRight(bytes32 left, bytes32 right)
        external
        view
        returns (bytes32 result)
    {
        if (uint256(left) >= BN254_SCALAR_MODULUS || uint256(right) >= BN254_SCALAR_MODULUS) {
            revert PoseidonCallFailed();
        }
        (bool ok, bytes memory data) = poseidon.staticcall(
            abi.encodeWithSignature("poseidon(uint256[2])", uint256(left), uint256(right))
        );
        if (!ok || data.length < 32) revert PoseidonCallFailed();
        uint256 value;
        assembly ("memory-safe") { value := mload(add(data, 32)) }
        if (value >= BN254_SCALAR_MODULUS) revert PoseidonCallFailed();
        result = bytes32(value);
    }
}